#!/bin/zsh
# AWS Login
local _aws_profile _azure_user _azure_url

_aws_profile=$1
_azure_user=${2:$AZURE_DEFAULT_USERNAME}
_azure_url=${AZURE_AD_URL:"https://microsoftonline.com/"}

(
  if test -n "${AWS_PROFILE}" -a -z "${_aws_profile}"; then
    _cmd_args="${AWS_PROFILE}";
  fi

  export AZURE_DEFAULT_PASSWORD="$(keychain_get_value "${_azure_url}" "${_azure_user}")"

  aws-azure-login \
    --enable-chrome-seamless-sso \
    --no-prompt \
    --profile "${_aws_profile}"
)

export AZURE_DEFAULT_PASSWORD=""
