#!/bin/zsh
# AWS Login
local _aws_profile _azure_user _azure_url

_azure_url="https://myapps.microsoftonline.com/"

_aws_profile="$1"
_azure_user="$2"

(
  export AZURE_DEFAULT_PASSWORD="$(keychain_get_value \
    "${AZURE_AD_URL:=$_azure_url}" "${_azure_user:=$AZURE_DEFAULT_USERNAME}")"

  aws-azure-login \
    --enable-chrome-seamless-sso \
    --no-prompt \
    --profile "${_aws_profile:=$AWS_PROFILE}"
)

export AZURE_DEFAULT_PASSWORD=""
