#!/usr/bin/env zsh
###################################
# Create Digital Ocean Server
#
# $1 = Name of Server (Required)
# $2 = Region Slug    (Default "nyc2")
# $3 = Image Slug     (Default "ubuntu-14-04-x64")
# $4 = Image Size     (Default "1gb")

local NAME REGION IMAGE SIZE SSH_KEY_ID

if [[ "$1" == "" ]]; then return 1; else NAME=$1; fi
if [[ "$2" == "" ]]; then REGION="nyc2"; else REGION="$2"; fi
if [[ "$3" == "" ]]; then IMAGE="ubuntu-16-04-x64"; else IMAGE="$3"; fi
if [[ "$4" == "" ]]; then SIZE="1gb"; else SIZE="$4"; fi

doctl compute droplet create $NAME \
  --region $REGION \
  --image $IMAGE \
  --size $SIZE \
  --ssh-keys $SSH_KEY_ID
