#!/bin/zsh
# Pull value from MacOS Keychain
#
# All args are optional, but require "" to avoid moving them positionally if an argument
# is blank.
#
# Usage:
#   1 - Service Name. Usually URL.
#   2 - Account name. Usually username.
#   3 - Comment. Additional filtering description.
#   4 - Label

# Args/Flag
local sec_find_cmd _sec
# 1=[Service]
local s_service=${1}
# 2=[Account Name]
local a_account=${2}
# 3=[Comment]
local j_comment=${3=}
# 4=[Label]
local l_label=${4=}

sec_find_cmd=("$(command -v security)" "find-generic-password")

if test ${s_service}; then
    sec_find_cmd+=("-s")
    sec_find_cmd+=(${s_service})
fi

if test ${a_account}; then
  sec_find_cmd+=("-a")
  sec_find_cmd+=(${a_account})
fi

if test ${j_comment}; then
  sec_find_cmd+=("-j")
  sec_find_cmd+=(${j_comment})
fi

if test ${l_label}; then
  sec_find_cmd+=("-l")
  sec_find_cmd+=(${l_label})
fi

sec_find_cmd+=("-w")

_sec=$(eval "${sec_find_cmd[@]}" 2>&1)

if test $? -eq 0; then
  print "${_sec}";
else
  (
    printf 'Unable to get keychain value for ('
    printf ' service: %s |' ${s_service}
    printf ' account: %s |' ${a_account}
    printf ' comment: %s |' ${j_comment}
    printf ' label: %s ' ${l_label}
    printf ') - %s\n' ${_sec}
  ) >&2
fi
