#!/bin/zsh

# Args/Flag
local sec_find_cmd _sec_cmd _sec _sec_return
# 1=[Service]
local s_service=${1}
# 2=[Account Name]
local a_account=${2}
# 3=[Comment]
local j_comment=${3=}
# 4=[Label]
local l_label=${4=}

sec_find_cmd=("$(command -v security)" "find-generic-password" "-w")
if test ${s_service}; then
    sec_find_cmd+=("-s")
    sec_find_cmd+=(${s_service})
fi

if test ${a_account}; then
  sec_find_cmd+=("-a")
  sec_find_cmd+=(${a_account})
fi

if test ${j_comment}; then
  sec_find_cmd+=("-j")
  sec_find_cmd+=(${j_comment})
fi

if test ${l_label}; then
  sec_find_cmd+=("-l")
  sec_find_cmd+=(${l_label})
fi

_sec_cmd=""
_sec=$(eval "${sec_find_cmd[@]}" 2>&1)
_sec_return=$?

if test ${_sec_return} -eq 0; then
  print "${_sec}";
else
  printf "Unable to get keychain value for %s||%s||%s||%s;\n%s" \
    ${s_service} \
    ${a_account} \
    ${j_comment} \
    ${l_label} \
    "$_sec"
fi

return ${_sec_return};
