#!/bin/zsh
#===============================================================================
# DO NOT EDIT THIS FILE DIRECTLY. This file is generated by running
# `make main.zsh` and any changes made here will be overwritten with each build.
#
# To edit the contents of this file, find the corresponding file in lib/ and
# make changes before running `make`.
#
#===============================================================================


_CUR_DIR=$(dirname "$0")
